### ISSUE TITLE
[Update Request] XRTModule need be updated

### ISSUE THREAD

**Issue by leaves-zwx** [Oneflow-Inc/oneflow-xrt#5]
oneflow 中 nn.Graph 的内部接口有一些 breaking update（譬如 finish_complie_and_init_runtime 被换成其他实现）。

XRTModule 需要随着一起更新。

**Comment by hjchen2** [comment]
这里是oneflow master代码修复了一个typo导致的问题，原来的Graph提供的接口是`finish_complie_and_init_runtime`，在最新的master里改成了`finish_compile_and_init_runtime`。

https://github.com/Oneflow-Inc/oneflow/commit/aef99812fbde6054916a19a4aa540810324127b0#diff-1657614b38666b43cab037646d3a3c80b1aef7ab526ef50bea84ee98ac9d6ae1L798-R809

**Comment by hjchen2** [comment]
https://github.com/Oneflow-Inc/oneflow-xrt/commit/63c275968bcf38196e6a60b62d780db7d5c1f887 这个commit已经修复了这个问题
