### ISSUE TITLE
Dismatch device between producer and consumer

### ISSUE THREAD

**Issue by leaves-zwx** [Oneflow-Inc/oneflow-xrt#7]
在测试 adam 的时候遇到1个问题：多个输入中，weight 和 weight_grad 是来自 non-cpu device，而 bias_correction_factor 来自 cpu device。导致在 compile 时，无法确定 input 到底是 device 上的还是 cpu 上的。

在oneflow的compile过程中，adam gen pass 中[插入 bias_correction_factor op 时](https://github.com/Oneflow-Inc/oneflow/blob/624bd004e0076f45024f30521fbfe0faf7dc6717/oneflow/core/job_rewriter/adam_optm.cpp#L158-L177)，一般插入的是 cpu 的 op。然后在之后的 build task graph 阶段，会再在 bias_correction_factor 和 adam optimizer 之间再插入一个 copy h2d 来完成转换。

但 xrt 的编译过程是发生在 build task graph 阶段之前，就无法检测到该 copy h2d 节点。其 adam xrt node 的输入就会来自不同的 device，编译成子图时，子图的 inputs 也就来自不同的 device 了。

**Comment by hjchen2** [comment]
如果adam本身是device的，那么它对应的xrt launch op也是device的，虽然xrt的编译发生在build task graph之前，但在build task graph的时候如果bias_correction_factor是cpu，而xrt launch op是device，依然会插入一个copy h2d的吧。

这样的话xrt launch op的bias_correction_factor还是device的。
